export const EMOJIS = {
    SEARCH: '🔎',
    CANCEL: '❌',
    NOT_FOUND: '🙈',
    SETTINGS: '⚙️',
    HEART: '🧡',
    FIRE: '🔥',
    LOVE: '🥰',
    SOUL: '😇',
    HOME: '🏠',
    MUTE: '🔇',
    SOUND: '🔊',
    EN: '🇬🇧',
    RU: '🇷🇺',
    MENU: '🧭',
} as const
