export const EMOJIS = {
    SEARCH: '🔎',
    CANCEL: '❌',
    NOT_FOUND: '🙈',
    SETTINGS: '⚙️',
    HEART: '🧡',
    FIRE: '🔥',
    LOVE: '🥰',
    SOUL: '😇',
    HOME: '🏠',
    MUTE: '🔇',
    SOUND: '🔊',
    EN: '🇬🇧',
    RU: '🇷🇺',
    MENU: '🧭',
    LOGO: '🌀',
    LEARNING: '‍👩‍🎓',
    TRAINING: '🏋️‍♂️',
    UP: '🔼',
    DOWN: '🔽',
    PALETTE: '🎨',
    FAVORITE: '⭐',
    VIEW: '👁️',
    CLIPBOARD: '📋',
} as const
