export const SYMBOLS = {
    UP: '▲',
    DOWN: '▼',
    ASCENDING: '↑',
    DESCENDING: '↓',
    MULTIPLY: '×',
    SPACE: ' ',
    CHECK: '✓',
    SLASH: '/',
    DOUBLE_NOTE: '♪♪',
    LOADING: '↻',
    WARNING: '⚠',
    COLON: ':',
    COLON_SPACE: ': ',
    ASTERISK: '*',
} as const
