import { VALUES } from 'src/shared/const/values.ts'
import { SYMBOLS } from 'src/shared/const/symbols.ts'
import { EMOJIS } from 'src/shared/const/emojis.ts'

export const TEXTS = {
    [VALUES.EN]: {
        APP_NAME: 'RosMosDev',
        APP_ACRONYM: 'RMD',
        APP_DESCRIPTION:
            'RosMosDev (RMD) is a card-based app for learning web development and preparing for job interviews',
        APP_SLOGAN: 'Web abyss to learning bliss!',
        SOMETHING_WENT_WRONG: 'Something went wrong...',
        CARD_SEARCH: 'Card search',
        LOADING: 'Loading',
        SORT_ALPHABET_ASCENDING: `${SYMBOLS.ASCENDING} Alphabet`,
        SORT_ALPHABET_DESCENDING: `${SYMBOLS.DESCENDING} Alphabet`,
        ALL: 'All',
        UNCATEGORIZED: 'Uncategorized',
        CARDS_NOT_FOUND: `Cards not found ${EMOJIS.NOT_FOUND}`,
        UNKNOWN_ERROR: 'Unknown error',
        RESTART_APP: 'Restart app? (Enter/Escape)',
        AUTO_RESTART: 'Auto restart in',
        AUTO_RESTART_CANCELED: 'Auto restart canceled',
        APP: 'App',
        LANGUAGE: 'Language',
        ENGLISH: 'English',
        RUSSIAN: 'Russian',
        DEBUG: 'Debug',
        DISPLAY_MARKUP: 'Display markup',
        DEBUG_MODE: 'Debug mode',
        THROW_ERROR: 'Throw error',
        SHOW_ERROR: 'Show error',
        HIDE_ERROR: 'Hide error',
        VERSION: 'Version:',
        BUILD: 'Build:',
        GITHUB: 'GitHub:',
        DEDICATION: 'For learners by learner',
        SETTINGS: 'Settings',
        INFO: 'Info',
        DEBUG_ERROR: 'Debug error',
        OCEAN: 'Ocean',
        BEACH: 'Beach',
        FIREPLACE: 'Fireplace',
        MOTIVATE: 'Motivate',
        WALKING: 'Walking',
        PAIN: 'Pain',
        BACKGROUND: 'Background',
        TYPE: 'Type',
        COLOR: 'Color',
        RANDOM_GRADIENT: 'Random gradient',
        WALLPAPER: 'Wallpaper',
        WALLPAPERS: 'Wallpapers',
        RANDOM_WALLPAPER: 'Random wallpaper',
        VIDEO: 'Video',
        VIDEOS: 'Videos',
        WALLPAPER1: 'Bliss',
        WALLPAPER2: 'The Persistence of Memory',
        WALLPAPER3: 'The Last Supper',
        WALLPAPER4: 'Morning in a Pine Forest',
        OVERLAY: 'Overlay',
        NEW_RANDOM_GRADIENT: 'New random gradient',
        LOAD_RANDOM_WALLPAPER: 'Load random wallpaper',
        CREATED: 'Created:',
        UPDATED: 'Updated:',
        CARDS: 'Cards',
        SHOW_CARD_CATEGORIES: 'Show card categories',
        SHOW_CARD_ID: 'Show card ID',
        SHOW_CARD_DATE: 'Show date and time of card creation/update',
        SHOW_CONNECTION_ALWAYS: 'Always show network status',
        RESET: 'Reset',
        RESTORE_DEFAULT_SETTINGS: 'Restore default settings',
        CLEAR_SESSION_STORAGE: 'Clear session storage',
        CLEAR_LOCAL_STORAGE: 'Clear local storage',
        PROFILE: 'Profile',
        LOGIN: 'Sign in with Google',
        LOGOUT: 'Logout',
        GUEST: 'Guest',
        IDENTIFIER: 'Identifier',
        USER: 'User',
        NAME: 'Name',
        MAIL: 'Mail',
        USER_PICTURE: 'User picture',
        CREATE_NEW_CARD: 'Create new card',
        REQUIRED_FIELD: 'Required field',
        TITLE: 'Title',
        TAGS: 'Comma separated tags',
        CONTENT: 'Content',
        CREATE: 'Create',
        CLEAR: 'Clear',
        INVALID_MAIL: 'Invalid mail',
        OFFICIAL_CARDS: 'Official cards',
        CUSTOM_CARDS: 'Custom cards',
        GUEST_CREATE_CARDS: 'In guest mode to create cards you need to wait for their verification',
        USER_CREATE_CARDS: 'An authorized user can create cards without verifying them',
    },
    [VALUES.RU]: {
        APP_NAME: 'РосМосДев',
        APP_ACRONYM: 'РМД',
        APP_DESCRIPTION:
            'РосМосДев (РМД) — это приложение с карточками для изучения веб-разработки и подготовки к собеседованиям',
        APP_SLOGAN: 'Из веб-тьмы — к вершинам мечты!',
        SOMETHING_WENT_WRONG: 'Что-то пошло не так...',
        CARD_SEARCH: 'Поиск карточек',
        LOADING: 'Загрузка',
        SORT_ALPHABET_ASCENDING: `${SYMBOLS.ASCENDING} Алфавит`,
        SORT_ALPHABET_DESCENDING: `${SYMBOLS.DESCENDING} Алфавит`,
        ALL: 'Все',
        UNCATEGORIZED: 'Без категории',
        CARDS_NOT_FOUND: `Карточки не найдены ${EMOJIS.NOT_FOUND}`,
        UNKNOWN_ERROR: 'Неизвестная ошибка',
        RESTART_APP: 'Перезапустить приложение? (Enter/Escape)',
        AUTO_RESTART: 'Автоматический перезапуск через',
        AUTO_RESTART_CANCELED: 'Автоматический перезапуск отменён',
        APP: 'Приложение',
        LANGUAGE: 'Язык',
        ENGLISH: 'Английский',
        RUSSIAN: 'Русский',
        DEBUG: 'Отладка',
        DISPLAY_MARKUP: 'Отображать разметку',
        DEBUG_MODE: 'Режим отладки',
        THROW_ERROR: 'Вызвать ошибку',
        SHOW_ERROR: 'Показать ошибку',
        HIDE_ERROR: 'Скрыть ошибку',
        VERSION: 'Версия:',
        BUILD: 'Сборка:',
        GITHUB: 'ГитХаб:',
        DEDICATION: 'Для изучающих от изучающего',
        SETTINGS: 'Настройки',
        INFO: 'Информация',
        DEBUG_ERROR: 'Отладочная ошибка',
        OCEAN: 'Океан',
        BEACH: 'Пляж',
        FIREPLACE: 'Камин',
        MOTIVATE: 'Мотивация',
        WALKING: 'Ходьба',
        PAIN: 'Боль',
        BACKGROUND: 'Фон',
        TYPE: 'Тип',
        COLOR: 'Цвет',
        RANDOM_GRADIENT: 'Случайный градиент',
        WALLPAPER: 'Обои',
        WALLPAPERS: 'Обои',
        RANDOM_WALLPAPER: 'Случайные обои',
        VIDEO: 'Видео',
        VIDEOS: 'Видеоролики',
        WALLPAPER1: 'Безмятежность',
        WALLPAPER2: 'Постоянство памяти',
        WALLPAPER3: 'Тайная вечеря',
        WALLPAPER4: 'Утро в сосновом лесу',
        OVERLAY: 'Затемнение',
        NEW_RANDOM_GRADIENT: 'Новый случайный градиент',
        LOAD_RANDOM_WALLPAPER: 'Загрузить случайные обои',
        CREATED: 'Создано:',
        UPDATED: 'Обновлено:',
        CARDS: 'Карточки',
        SHOW_CARD_CATEGORIES: 'Показывать категории карточки',
        SHOW_CARD_ID: 'Показывать идентификатор карточки',
        SHOW_CARD_DATE: 'Показывать дату и время создания/обновления карточки',
        SHOW_CONNECTION_ALWAYS: 'Всегда показывать статус сети',
        RESET: 'Сброс',
        RESTORE_DEFAULT_SETTINGS: 'Восстановить настройки по умолчанию',
        CLEAR_SESSION_STORAGE: 'Очистить хранилище сеанса',
        CLEAR_LOCAL_STORAGE: 'Очистить локальное хранилище',
        PROFILE: 'Профиль',
        LOGIN: 'Авторизоваться с помощью Google',
        LOGOUT: 'Выйти',
        GUEST: 'Гость',
        IDENTIFIER: 'Идентификатор',
        USER: 'Пользователь',
        NAME: 'Имя',
        MAIL: 'Почта',
        USER_PICTURE: 'Пользовательское фото',
        CREATE_NEW_CARD: 'Создание новой карточки',
        REQUIRED_FIELD: 'Обязательное поле',
        TITLE: 'Заголовок',
        TAGS: 'Теги, разделенные запятыми',
        CONTENT: 'Контент',
        CREATE: 'Создать',
        CLEAR: 'Очистить',
        INVALID_MAIL: 'Невалидная почта',
        OFFICIAL_CARDS: 'Официальные карточки',
        CUSTOM_CARDS: 'Пользовательские карточки',
        GUEST_CREATE_CARDS: 'В гостевом режиме для создания карточек нужно дождаться их верификации',
        USER_CREATE_CARDS: 'Авторизованный пользователь может создавать карточки без их верификации',
    },
} as const
