import { VALUES } from 'src/shared/const/values.ts'
import { SYMBOLS } from 'src/shared/const/symbols.ts'
import { EMOJIS } from 'src/shared/const/emojis.ts'

export const TEXTS = {
    [VALUES.EN]: {
        APP_NAME: 'RosMosDev',
        APP_ACRONYM: 'RMD',
        APP_DESCRIPTION:
            'RosMosDev (RMD) is a card-based app for learning web development and preparing for job interviews',
        APP_SLOGAN: 'Web abyss to learning bliss!',
        SOMETHING_WENT_WRONG: 'Something went wrong...',
        CARD_SEARCH: 'Card search',
        LOADING: 'Loading',
        SORT_ALPHABET_ASCENDING: `${SYMBOLS.ASCENDING} Alphabet`,
        SORT_ALPHABET_DESCENDING: `${SYMBOLS.DESCENDING} Alphabet`,
        ALL: 'All',
        UNCATEGORIZED: 'Uncategorized',
        CARDS_NOT_FOUND: `Cards not found ${EMOJIS.NOT_FOUND}`,
        UNKNOWN_ERROR: 'Unknown error',
        RESTART_APP: 'Restart app? (Enter/Escape)',
        AUTO_RESTART: 'Auto restart in',
        AUTO_RESTART_CANCELED: 'Auto restart canceled',
        APP: 'App',
        LANGUAGE: 'Language',
        ENGLISH: 'English',
        RUSSIAN: 'Russian',
        DEBUG: 'Debug',
        DISPLAY_MARKUP: 'Display markup',
        DEBUG_MODE: 'Debug mode',
        THROW_ERROR: 'Throw error',
        VERSION: 'Version:',
        BUILD: 'Build:',
        GITHUB: 'GitHub:',
        DEDICATION: 'For learners by learner',
        SETTINGS: 'Settings',
        INFO: 'Info',
        DEBUG_ERROR: 'Debug error',
        OCEAN: 'Ocean',
        BEACH: 'Beach',
        FIREPLACE: 'Fireplace',
        MOTIVATE: 'Motivate',
        WALKING: 'Walking',
        PAIN: 'Pain',
        BACKGROUND: 'Background',
        TYPE: 'Type',
        COLOR: 'Color',
        RANDOM_GRADIENT: 'Random gradient',
        WALLPAPER: 'Wallpaper',
        WALLPAPERS: 'Wallpapers',
        RANDOM_WALLPAPER: 'Random wallpaper',
        VIDEO: 'Video',
        VIDEOS: 'Videos',
        WALLPAPER1: 'Bliss',
        WALLPAPER2: 'The Persistence of Memory',
        WALLPAPER3: 'The Last Supper',
        WALLPAPER4: 'Morning in a Pine Forest',
        OVERLAY: 'Overlay',
        NEW_RANDOM_GRADIENT: 'New random gradient',
        LOAD_RANDOM_WALLPAPER: 'Load random wallpaper',
    },
    [VALUES.RU]: {
        APP_NAME: 'РосМосДев',
        APP_ACRONYM: 'РМД',
        APP_DESCRIPTION:
            'РосМосДев (РМД) — это приложение с карточками для изучения веб-разработки и подготовки к собеседованиям',
        APP_SLOGAN: 'Из веб-тьмы — к вершинам мечты!',
        SOMETHING_WENT_WRONG: 'Что-то пошло не так...',
        CARD_SEARCH: 'Поиск карточек',
        LOADING: 'Загрузка',
        SORT_ALPHABET_ASCENDING: `${SYMBOLS.ASCENDING} Алфавит`,
        SORT_ALPHABET_DESCENDING: `${SYMBOLS.DESCENDING} Алфавит`,
        ALL: 'Все',
        UNCATEGORIZED: 'Без категории',
        CARDS_NOT_FOUND: `Карточки не найдены ${EMOJIS.NOT_FOUND}`,
        UNKNOWN_ERROR: 'Неизвестная ошибка',
        RESTART_APP: 'Перезапустить приложение? (Enter/Escape)',
        AUTO_RESTART: 'Автоматический перезапуск через',
        AUTO_RESTART_CANCELED: 'Автоматический перезапуск отменён',
        APP: 'Приложение',
        LANGUAGE: 'Язык',
        ENGLISH: 'Английский',
        RUSSIAN: 'Русский',
        DEBUG: 'Отладка',
        DISPLAY_MARKUP: 'Отображать разметку',
        DEBUG_MODE: 'Режим отладки',
        THROW_ERROR: 'Вызвать ошибку',
        VERSION: 'Версия:',
        BUILD: 'Сборка:',
        GITHUB: 'ГитХаб:',
        DEDICATION: 'Для изучающих от изучающего',
        SETTINGS: 'Настройки',
        INFO: 'Информация',
        DEBUG_ERROR: 'Отладочная ошибка',
        OCEAN: 'Океан',
        BEACH: 'Пляж',
        FIREPLACE: 'Камин',
        MOTIVATE: 'Мотивация',
        WALKING: 'Ходьба',
        PAIN: 'Боль',
        BACKGROUND: 'Фон',
        TYPE: 'Тип',
        COLOR: 'Цвет',
        RANDOM_GRADIENT: 'Случайный градиент',
        WALLPAPER: 'Обои',
        WALLPAPERS: 'Обои',
        RANDOM_WALLPAPER: 'Случайные обои',
        VIDEO: 'Видео',
        VIDEOS: 'Видеоролики',
        WALLPAPER1: 'Безмятежность',
        WALLPAPER2: 'Постоянство памяти',
        WALLPAPER3: 'Тайная вечеря',
        WALLPAPER4: 'Утро в сосновом лесу',
        OVERLAY: 'Затемнение',
        NEW_RANDOM_GRADIENT: 'Новый случайный градиент',
        LOAD_RANDOM_WALLPAPER: 'Загрузить случайные обои',
    },
} as const
