import { VALUES } from 'src/shared/const/values.ts'
import { SYMBOLS } from 'src/shared/const/symbols.ts'
import { EMOJIS } from 'src/shared/const/emojis.ts'

export const TEXTS = {
    [VALUES.EN]: {
        APP_NAME: 'RosMosDev',
        APP_ACRONYM: 'RMD',
        APP_DESCRIPTION:
            'RosMosDev (RMD) is a card-based app for learning web development and preparing for job interviews',
        APP_SLOGAN: 'Web abyss to learning bliss!',
        SOMETHING_WENT_WRONG: 'Something went wrong...',
        CARD_SEARCH: 'Card search',
        LOADING: 'Loading...',
        SORT_ALPHABET_ASCENDING: `${SYMBOLS.ASCENDING} Alphabet`,
        SORT_ALPHABET_DESCENDING: `${SYMBOLS.DESCENDING} Alphabet`,
        ALL: 'All',
        UNCATEGORIZED: 'Uncategorized',
        CARDS_NOT_FOUND: `Cards not found ${EMOJIS.NOT_FOUND}`,
        UNKNOWN_ERROR: 'Unknown error',
        RESTART_APP: 'Restart app? (Enter/Escape)',
        AUTO_RESTART: 'Auto restart in',
        AUTO_RESTART_CANCELED: 'Auto restart canceled',
        APP: 'App',
        LANGUAGE: 'Language',
        ENGLISH: '🇺🇸 English',
        RUSSIAN: '🇷🇺 Russian',
        DEBUG: 'Debug',
        DISPLAY_MARKUP: 'Display markup',
        DEBUG_MODE: 'Debug model',
        THROW_ERROR: 'Throw error',
        VERSION: 'Version:',
        BUILD: 'Build:',
        GITHUB: 'GitHub:',
        DEDICATION: 'For learners by learner',
        SETTINGS: 'Settings',
        INFO: 'Info',
        DEBUG_ERROR: 'Debug error',
    },
    [VALUES.RU]: {
        APP_NAME: 'РосМосДев',
        APP_ACRONYM: 'РМД',
        APP_DESCRIPTION:
            'РосМосДев (РМД) — это приложение с карточками для изучения веб-разработки и подготовки к собеседованиям',
        APP_SLOGAN: 'Из веб-тьмы — к вершинам мечты!',
        SOMETHING_WENT_WRONG: 'Что-то пошло не так...',
        CARD_SEARCH: 'Поиск карточек',
        LOADING: 'Загрузка...',
        SORT_ALPHABET_ASCENDING: `${SYMBOLS.ASCENDING} Алфавит`,
        SORT_ALPHABET_DESCENDING: `${SYMBOLS.DESCENDING} Алфавит`,
        ALL: 'Все',
        UNCATEGORIZED: 'Без категории',
        CARDS_NOT_FOUND: `Карточки не найдены ${EMOJIS.NOT_FOUND}`,
        UNKNOWN_ERROR: 'Неизвестная ошибка',
        RESTART_APP: 'Перезапустить приложение? (Enter/Escape)',
        AUTO_RESTART: 'Автоматический перезапуск через',
        AUTO_RESTART_CANCELED: 'Автоматический перезапуск отменён',
        APP: 'Приложение',
        LANGUAGE: 'Язык',
        ENGLISH: 'Английский',
        RUSSIAN: 'Русский',
        DEBUG: 'Отладка',
        DISPLAY_MARKUP: 'Отображать разметку',
        DEBUG_MODE: 'Режим отладки',
        THROW_ERROR: 'Вызвать ошибку',
        VERSION: 'Версия:',
        BUILD: 'Сборка:',
        GITHUB: 'ГитХаб:',
        DEDICATION: 'Для изучающих от изучающего',
        SETTINGS: 'Настройки',
        INFO: 'Информация',
        DEBUG_ERROR: 'Отладочная ошибка',
    },
} as const
