export const TIMINGS = {
    SECOND: 1_000,
    RESTART_SECONDS: 30,
    MESSAGE_APPEAR: 0.1,
    RISE_ANIMATION: 1.5,
    SPIN_ANIMATION: 2,
    BEATS_ANIMATION: 0.25,
    TRANSITION_TRANSFORM: 0.5,
    CHECK_TRANSITION: 0.2,
    ROTATE_ANIMATION: 10,
} as const
