export const TITLES = {
    en: {
        SEARCH: 'Search cards by titles, tags and content',
        CLEAR_SEARCH: 'Clear search',
        CARD_SORTING: 'Card sorting',
        CARD_CATEGORIES: 'Card categories',
        OPEN_SETTINGS: 'Open settings',
        OPEN_DASHBOARD: 'Open dashboard',
        OPEN_MENU: 'Open menu',
        CLOSE_MENU: 'Close menu',
        LOVE: 'Love',
        SOUL: 'Soul',
        ENABLE_BACKGROUND_SOUND: 'Enable background sound',
        MUTE_BACKGROUND_SOUND: 'Mute background sound',
        ENABLE_LEARNING_MODE: 'Enable learning mode',
        ENABLE_TRAINING_MODE: 'Enable training mode',
        OPEN_CARD: 'Open card',
        CLOSE_CARD: 'Close card',
        HIGHLIGHT_CARD: 'Highlight card',
        COPY_TO_CLIPBOARD: 'Copy to clipboard',
    },
    ru: {
        SEARCH: 'Поиск карточек по заголовкам, тегам и контенту',
        CLEAR_SEARCH: 'Очистить поиск',
        CARD_SORTING: 'Сортировка карточек',
        CARD_CATEGORIES: 'Категории карточек',
        OPEN_SETTINGS: 'Открыть настройки',
        OPEN_DASHBOARD: 'Открыть дашборд',
        OPEN_MENU: 'Открыть меню',
        CLOSE_MENU: 'Закрыть меню',
        LOVE: 'Любовью',
        SOUL: 'Душой',
        ENABLE_BACKGROUND_SOUND: 'Включить фоновый звук',
        MUTE_BACKGROUND_SOUND: 'Заглушить фоновый звук',
        ENABLE_LEARNING_MODE: 'Включить режим изучения',
        ENABLE_TRAINING_MODE: 'Включить режим тренировки',
        OPEN_CARD: 'Открыть карточку',
        CLOSE_CARD: 'Закрыть карточку',
        HIGHLIGHT_CARD: 'Выделить карточку',
        COPY_TO_CLIPBOARD: 'Копировать в буфер обмена',
    },
} as const
