export const TITLES = {
    en: {
        SEARCH: 'Search cards by titles, tags and content',
        CLEAR_SEARCH: 'Clear search',
        CARD_SORTING: 'Card sorting',
        CARD_CATEGORIES: 'Card categories',
        OPEN_SETTINGS: 'Open settings',
        OPEN_DASHBOARD: 'Open dashboard',
        LOVE: 'Love',
        SOUL: 'Soul',
        ENABLE_BACKGROUND_SOUND: 'Enable background sound',
        MUTE_BACKGROUND_SOUND: 'Mute background sound',
    },
    ru: {
        SEARCH: 'Поиск карточек по заголовкам, тегам и контенту',
        CLEAR_SEARCH: 'Очистить поиск',
        CARD_SORTING: 'Сортировка карточек',
        CARD_CATEGORIES: 'Категории карточек',
        OPEN_SETTINGS: 'Открыть настройки',
        OPEN_DASHBOARD: 'Открыть дашборд',
        LOVE: 'Любовью',
        SOUL: 'Душой',
        ENABLE_BACKGROUND_SOUND: 'Включить фоновый звук',
        MUTE_BACKGROUND_SOUND: 'Заглушить фоновый звук',
    },
} as const
