export const VALUES = {
    EMPTY_STRING: '',
    COMMA: ',',
    COMMA_SPACE: ', ',
    NEW_LINE: '\n',
    DOUBLE_NEW_LINE: '\n\n',
    EN: 'en',
    RU: 'ru',
    MEDIUM_SIZE: '1.5rem',
    BIG_SIZE: '2rem',
    LARGE_SIZE: '3rem',
    VERSION: '0.2.3',
    BUILD: '040724',
    BEATS: 'beats',
    BACKGROUND_SOUND_VOLUME: 0.1,
    STRETCH: 'stretch',
    END: 'end',
    DISPATCH: 'dispatch',
} as const
